#!/bin/bash

VERSION="1.0"

build_repo() {
    if [ ! -d $1 ];
    then
        git clone https://github.com/cortoproject/${1}.git
    else
        cd $1
        git fetch origin
        git reset --hard origin/master
        git clean -xdf
        cd ..
    fi
    cd $1
    if [ -f "configure" ];
    then
        . ./configure
    fi
    if [ -f "project.json" ];
    then
        corto rakefile
    fi
    rake
    cd ..
}

install_corto () {
    set -e
    set -u

    UNAME=$(uname)
    ARCHITECTURE=$(uname -m)
    PREFIX="/usr/local"
    FILENAME="corto"
    INSTALL_TMPDIR="corto-src"

    # Check supported OS
    if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" ] ; then
        >&2 echo "corto: sorry, this OS is not supported yet!"
        exit 1
    fi
    if [ "$UNAME" = "Darwin" ] ; then
        if [ "i386" != "$(uname -p)" -o "1" != "$(sysctl -n hw.cpu64bit_capable 2>/dev/null || echo 0)" ] ; then
          >&2 echo "corto: only 64-bit Intel processors are supported at this time!"
          exit 1
        fi
    fi

    if [ "$UNAME" = "Linux" ] ; then
        sudo apt-get -y --force-yes install git build-essential rake libffi-dev libxml2-dev flex bison libcurl4-openssl-dev libssl-dev
    elif [ "$UNAME" = "Darwin" ] ; then
        sudo xcode-select --install
    fi

    echo
    echo "Hi! Downloading Corto package repositories..."
    mkdir -p "$INSTALL_TMPDIR"

    cd $INSTALL_TMPDIR
    build_repo "corto"
    build_repo "argparse"
    build_repo "driver-tool-locate"
    build_repo "driver-tool-rakefile"
    build_repo "driver-tool-build"
    build_repo "driver-tool-default"
    build_repo "driver-tool-clean"
    build_repo "driver-tool-rebuild"
    build_repo "driver-tool-install"
    build_repo "driver-tool-uninstall"
    build_repo "driver-tool-add"
    build_repo "driver-tool-remove"
    build_repo "driver-tool-create"
    build_repo "driver-tool-tar"
    build_repo "driver-tool-untar"
    build_repo "driver-tool-list"
    build_repo "driver-tool-run"
    build_repo "cdiff"
    build_repo "g"
    build_repo "driver-tool-pp"
    build_repo "c-binding"
    build_repo "json"
    build_repo "xml"
    build_repo "vm"
    build_repo "ic"
    build_repo "corto-language"
    build_repo "test"
    build_repo "driver-tool-test"

    echo
    corto --logo
    echo
    echo "Corto "`~/.corto/bin/corto --minor`" successfully built!"
}

install_corto
