#!/bin/sh
VERSION="0.2"

install_corto_fail() {
    >&2 echo "corto: installation failed :("
    rm -rf "$INSTALL_TMPDIR"
    sudo rm -f "/usr/local/bin/corto"
    sudo rm -f "/usr/local/bin/corto.$VERSION"
    sudo rm -f "/usr/local/lib/libcorto.so"
    sudo rm -f "/usr/local/lib/libcorto.so.$VERSION"
    sudo rm -rf "/usr/local/lib/corto/$VERSION"
    sudo rm -rf "/usr/local/include/corto/$VERSION"
    sudo rm -rf "/usr/local/etc/corto/$VERSION"
    sudo rm -rf "$HOME/.corto"

    # Get rid of deprecated installation
    sudo rm -f "/usr/bin/corto"
    sudo rm -f "/usr/bin/corto.*"
    sudo rm -f "/usr/lib/libcorto.so"
    sudo rm -f "/usr/lib/libcorto.so.*"
    sudo rm -rf "/usr/lib/corto/*"
    sudo rm -rf "/usr/include/corto/*"
    sudo rm -rf "/usr/etc/corto/*"    
}

install_corto () {
    set -e
    set -u

    UNAME=$(uname)
    ARCHITECTURE=$(uname -p)
    PREFIX="/usr/local"
    FILENAME="corto"
    TARBALL_URL="https://raw.githubusercontent.com/cortoproject/packages/master/corto/$UNAME-$ARCHITECTURE/corto.tar.gz"
    INSTALL_TMPDIR="$HOME/.corto/.download"

    # Check supported OS
    if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" ] ; then
        >&2 echo "corto: sorry, this OS is not supported yet!"
        exit 1
    fi
    if [ "$UNAME" = "Darwin" ] ; then
        if [ "i386" != "$(uname -p)" -o "1" != "$(sysctl -n hw.cpu64bit_capable 2>/dev/null || echo 0)" ] ; then
          >&2 echo "corto: only 64-bit Intel processors are supported at this time!"
          exit 1
        fi
    fi

    # Ask for password upfront
    if sudo -n true 2>/dev/null; then
        true
    else
        echo
        echo "Hi! The installer will install corto to /usr/local."
        echo "Please provide the password for $USER:"
        sudo true
    fi

    echo
    echo "Stand by, this will just take a second..."
    echo

    trap install_corto_fail EXIT

    # Remove existing cortex version
    if [ "`which cortex`" != "" ]  ; then
        OLD_VERSION=`cortex -v`
        echo "corto: removing your existing cortex distribution ($OLD_VERSION)"
        sudo rm -f "/usr/bin/cortex"
        sudo rm -f "/usr/bin/cortex.$OLD_VERSION"
        sudo rm -f "/usr/lib/libcortex.so"
        sudo rm -f "/usr/lib/libcortex.so.$OLD_VERSION"
        sudo rm -rf "/usr/lib/cortex/$OLD_VERSION"
        sudo rm -rf "/usr/include/cortex/$OLD_VERSION"
    fi

    # Remove existing versions
    if [ "`which corto`" != "" ]  ; then
        if [ "`corto -v`" != "0.2.0-alpha" ] ; then
            OLD_VERSION=`corto --minor`
        else
            OLD_VERSION=`corto -v`
        fi
        echo "corto: removing your existing corto distribution ("`corto -v`")"
        sudo rm -f "/usr/local/bin/corto"
        sudo rm -f "/usr/local/bin/corto.$OLD_VERSION"
        sudo rm -f "/usr/local/lib/libcorto.so"
        sudo rm -f "/usr/local/lib/libcorto.so.$OLD_VERSION"
        sudo rm -rf "/usr/local/lib/corto/$OLD_VERSION"
        sudo rm -rf "/usr/local/include/corto/$OLD_VERSION"
        sudo rm -rf "/usr/local/etc/corto/$OLD_VERSION"
    fi

    mkdir -p "$HOME/.corto"
    sudo mkdir -p "$PREFIX/lib/corto/$VERSION"

    echo "corto: downloading distribution"
    rm -rf "$INSTALL_TMPDIR"
    mkdir -p "$INSTALL_TMPDIR"

    sudo curl --progress-bar --fail "$TARBALL_URL" | tar -xzf - -C "$INSTALL_TMPDIR"

    echo "corto: installing files"
    sudo cp -a "$INSTALL_TMPDIR/." "/usr/local"
    rm -rf "$INSTALL_TMPDIR"
    sudo mv "/usr/local/bin/corto" "/usr/local/bin/corto.$VERSION"
    sudo ln -s "/usr/local/bin/corto.$VERSION" "/usr/local/bin/corto"
    echo "corto: done!"
    echo

    echo "Corto "`corto -v`" successfully installed!"
    echo
    echo "Now create your first project with:"
    echo
    echo "   $ corto create myApp"
    echo "   $ cd myApp"
    echo "   $ corto run"
    echo

    trap - EXIT
}

install_corto
