#!/bin/bash
install_corto_fail() {
    echo "Installation failed :("
}

clone_repo() {
    if [ ! -d $1 ];
    then
        git clone https://github.com/cortoproject/${1}.git
    else
        cd $1
        git fetch origin
        git reset --hard origin/master
        git clean -xdf
        cd ..
    fi
}

install_corto () {
    set -u

    UNAME=$(uname)
    ARCHITECTURE=$(uname -m)
    INSTALL_TMPDIR="$HOME/corto/src"

    # Check supported OS
    if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" ] ; then
        >&2 echo "corto: sorry, this OS is not supported yet!"
        exit 1
    fi
    if [ "$UNAME" = "Darwin" ] ; then
        if [ "i386" != "$(uname -p)" -o "1" != "$(sysctl -n hw.cpu64bit_capable 2>/dev/null || echo 0)" ] ; then
          >&2 echo "corto: only 64-bit Intel processors are supported at this time!"
          exit 1
        fi
    fi

    if [ "$UNAME" = "Linux" ] ; then
        sudo apt-get -y install git build-essential libffi-dev libxml2-dev flex bison libcurl4-openssl-dev libssl-dev
    elif [ "$UNAME" = "Darwin" ] ; then
        pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
        rc=$?; if [ $rc != 0 ]; then
            echo "Looks like Xcode command-line tools are not installed. Run:"
            echo "  sudo xcode-select --install"
            echo
            echo "Then try installing corto again!"
            exit 1
        fi
    fi

    # Check if corto is installed
    corto --version
    rc=$?
    if [ $rc != 0 ]; then
        echo
        echo "Cortoscript requires a minimal corto/bake environment. To install, do:"
        echo "  curl https://corto.io/install-bake | sh"
        echo
        exit 1
    fi

    trap install_corto_fail EXIT

    echo
    echo "Installing cortoscript, this may take a few minutes..."

    # Create 'src' directory in corto
    mkdir -p "$INSTALL_TMPDIR"
    cd $INSTALL_TMPDIR

    echo "cloning cortoscript packages"
    clone_repo "driver-fmt-xml"
    clone_repo "driver-ext-xml"
    clone_repo "antlr4-cpp"
    clone_repo "script-parser"
    clone_repo "script-ast"
    clone_repo "script-ast-print"
    clone_repo "script-declare"
    clone_repo "driver-ext-corto"

    # Build projects
    echo "build projects"
    bake

    trap - EXIT
}

install_corto
